# Generated by Django 2.0 on 2018-03-13 21:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
    ]
