# Generated by Django 2.0 on 2018-03-18 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180318_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hard',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='article',
            name='importancy',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 14, 15, 3, 448793), verbose_name='date published'),
        ),
    ]
