# Generated by Django 2.0 on 2018-03-18 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20180318_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='exerciese_or_theory',
            field=models.CharField(blank=True, choices=[('exercise', 'exercise'), ('theory', 'theory')], max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 14, 42, 6, 844843), verbose_name='date published'),
        ),
    ]
