# Generated by Django 2.0 on 2018-03-18 13:53

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20180318_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientist',
            name='year',
        ),
        migrations.AddField(
            model_name='scientist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 14, 53, 31, 189725), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='scientist',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='0'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 14, 53, 31, 187707), verbose_name='date published'),
        ),
    ]
