# Generated by Django 2.0 on 2018-03-18 13:54

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20180318_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 14, 54, 28, 976330), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 14, 54, 28, 977331), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
